### PR TITLE
Add support for BuddyPress registration form.

### PR DESCRIPTION
**Pull request by dcavins**
Hi Collizo4sky-

I wanted to use your plugin with a BuddyPress installation, so I've extended it to provide a No CAPTCHA check on the BP registration page. Please let me know if you have any questions about how I've written the new code.

I've tested this new version pretty thoroughly with BuddyPress activated, but have not tested it extensively on a vanilla WP installation. If you run across any problems when BP is not installed or activated, please let me know.

Thanks!

-David

### CODE REVIEW

**Comment by w3guy** [comment]
Thanks for this. i will test and merge asap.

**Comment by w3guy** [comment]
Hi @dcavins, could you please rebase your master branch to be even with mine.

I earlier forgot to sync the master branch to be even with the SVN repo.

Am indeed very sorry for this complications.

**Comment by dcavins** [comment]
No problem. I'll open a new pull request from a different branch.

**Comment by w3guy** [comment]
Thank you.                                                                                                                                                                                                                                                                          Regards.Agbonghama Collins.                                                                                                                                                                                                                                         From: David CavinsSent: Tuesday, 4 August 2015 2:58 PMTo: Collizo4sky/No-CAPTCHA-reCAPTCHAReply To: Collizo4sky/No-CAPTCHA-reCAPTCHACc: Agbonghama CollinsSubject: Re: [No-CAPTCHA-reCAPTCHA] Add support for BuddyPress registration form. (#4)No problem. I'll open a new pull request from a different branch.

—Reply to this email directly or view it on GitHub.

**Pull request closed without merging**
