### PR TITLE
[fix #2] Allow network activation

### LINKED ISSUE #2: The plugin cannot be activated network wide
On a multisite install of WordPress, try to activate the plugin on the whole network fails and display the following error : 

`Fatal error: Class 'Ncr_Settings_Page' not found in /path/to/plugins/No-CAPTCHA-reCAPTCHA/no-captcha-recaptcha.php on line 29`

### PR DESCRIPTION
**Pull request by Fab1en**
This commit fixes issue #2 and allow network activation of the plugin.

### CODE REVIEW

**Comment by Fab1en** [comment]
I solved several issues with this pull request :
- allow the plugin to be activated network-wide, and in this case display the settings page on the network admin side
- make the plugin fully translation-ready, and provide the french translation
- remove warnings that display on first activation, when all options are not set
- list the available language for CAPTCHA from the WordPress language packs. To add another language, simply install a new core language pack. This way, the list will only show the languages you are interested in.

**Comment by w3guy** [comment]
Thanks for the fix. 

Didnt know about `wp_kses` function.

I will test later to be double sure it work perfectly.

**Comment by Fab1en** [comment]
Here is the codex page where you can find all the best practices for internationalizing plugins and themes : [I18n for WordPress Developers](http://codex.wordpress.org/I18n_for_WordPress_Developers). The `wp_kses` function is cited in the [HTML](http://codex.wordpress.org/I18n_for_WordPress_Developers#HTML) section.

**Comment by w3guy** [comment]
Am quite good at plugin i18n and l10nProblem was, I pushed the plugin out in ah hurry and pretty much forgot about it cos I was so busy with school work.                                                                                                                                                                                                                                                                          Regards.Agbonghama Collins.                                                                                                                                                                                                                                         From: FabienSent: Thursday, 23 July 2015 3:18 PMTo: Collizo4sky/No-CAPTCHA-reCAPTCHAReply To: Collizo4sky/No-CAPTCHA-reCAPTCHACc: Agbonghama CollinsSubject: Re: [No-CAPTCHA-reCAPTCHA] [fix #2] Allow network activation (#3)Here is the codex page where you can find all the best practices for internationalizing plugins and themes : I18n for WordPress Developers.

—Reply to this email directly or view it on GitHub.

**Comment by Fab1en** [comment]
Hi Agbonghama.
Did you find the time to check this pull request ?

**Comment by w3guy** [comment]
Hi, currently giving it a test now. you should hear from me soon.

Sorry for the delay.

**Comment by w3guy** [comment]
Hi @Fab1en i just sync the repo to be even with version 1.0.2 in WordPress SVN.

Could you please rebase your branch and then resubmit the pull request?

So sorry about this.

I only discovered this after merging your pull to the master.

**Comment by Fab1en** [comment]
I made a new pull request after your change to master : #6

**Comment by w3guy** [comment]
Quick question, how do you download a PR?Nevermind, just saw a quick tutorial that seem to work.                                                                                                                                                                                                                                                                          Regards.Agbonghama Collins.                                                                                                                                                                                                                                         From: FabienSent: Tuesday, 4 August 2015 4:16 PMTo: Collizo4sky/No-CAPTCHA-reCAPTCHAReply To: Collizo4sky/No-CAPTCHA-reCAPTCHACc: Agbonghama CollinsSubject: Re: [No-CAPTCHA-reCAPTCHA] [fix #2] Allow network activation (#3)I made a new pull request after your change to master : #6 

—Reply to this email directly or view it on GitHub.

**Pull request merged**
